language: python
python:
    - "3.6.3"
branches:
  only:
    - master
install:
    - cp contrib/.env-sample .env
    - pip install -q -r requirements.txt
    - python manage.py db upgrade
script:
    - python manage.py test
notifications:
    slack: $slack
